#
#  Description:  Units conversion aids.
#
#  Copyright (C) 2007, 2009 Austin Robot Technology                    
#
#  License: Modified BSD Software License Agreement
#
#  $Id$
#

#  @file
#  
#  @brief Units conversion constants.
#

# Unit conversion constants:
float64 INCHES_PER_FOOT = 12.0
float64 CM_PER_INCH = 2.54
float64 CM_PER_METER = 100.0
float64 METERS_PER_FOOT = 0.3048
float64 MMETERS_PER_KM = 1000000.0
float64 MMETERS_PER_MILE = 1609344.0
float64 METERS_PER_MILE = 1609.344
int64 SECONDS_PER_MINUTE = 60
int64 MINUTES_PER_HOUR = 60
int64 SECONDS_PER_HOUR = 3600
