#  Real-time cycle rates for various ART vehicle nodes.
# $Id$

#  All units are hertz (cycles/second).  This is not a published
#  message, it defines multi-language constants.

float64 APPLANIX        = 20.0
float64 BRAKE           = 20.0
float64 COMMANDER       = 10.0
float64 IOADR           = 10.0
float64 LASER_FUSION    = 10.0
float64 LASER_NOISE     = 10.0
float64 MAPLANES        = 5.0
float64 NAVIGATOR       = 20.0
float64 OBSERVERS       = 10.0
float64 PILOT           = 20.0
float64 PSEUDO_LASER    = 10.0
float64 SICKFAST        = 10.0
float64 STEERING        = 20.0
float64 THROTTLE        = 20.0
float64 VEHICLE_TF      = 5.0
